# Generated by Django 5.1.2 on 2024-10-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('computer_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=100)),
                ('window_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
            ],
        ),
    ]
