# Generated by Django 5.1.2 on 2024-10-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logevent_content_alter_logevent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevent',
            name='application',
            field=models.CharField(max_length=255),
        ),
    ]
